language: node_js

node_js:
  - 8
  
branches:
  only:
    - master

before_script:
  - git config --global user.email "eduadiez@gmail.com"
  - git config --global user.name "eduadiez"
  - git remote rm origin
  - git remote add origin https://user:${GITHUB_TOKEN}@github.com/user/repo.git
  
install:
  - travis_retry npm install -g @dappnode/dappnodesdk

script:
  - IPFS_PROVIDER=ipfs.infura.io IPFS_PROTO=https SILENT=true PROVIDER=wss://mainnet.infura.io/ws dappnodesdk publish patch

after_success:
  - ./push.sh
  
jobs:
  include:
    # Define the release stage that runs semantic-release
    - stage: release
      node_js: lts/*
      # Advanced: optionally overwrite your default `script` step to skip the tests
      deploy:
        provider: script
        skip_cleanup: true
        github-token: $GITHUB_TOKEN
        script: 
          - npx semantic-release
